# Generated by Django 5.0.6 on 2024-05-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pptFile', models.FileField(blank=True, null=True, upload_to='\\ppt')),
            ],
        ),
    ]
